[2025-08-09 18:13:37] Code validation failed: Validation error: Traceback (most recent call last):
  File "/app/play_script.py", line 70, in <module>
    main()
  File "/app/play_script.py", line 51, in main
    p.on_round_start(round_state, 990)
  File "/app/player.py", line 38, in on_round_start
    self.strong_hole_cards = self.evaluate_hole_card_strength(self.player_hands) if self.player_hands else False
  File "/app/player.py", line 133, in evaluate_hole_card_strength
    values = [self.card_rank(card) for card in hole_cards]
  File "/app/player.py", line 133, in <listcomp>
    values = [self.card_rank(card) for card in hole_cards]
  File "/app/player.py", line 251, in card_rank
    return rank_map.get(r, int(r))
ValueError: invalid literal for int() with base 10: 'A'

